### ISSUE TITLE
Logitech/Saitek radio panel problem

### ISSUE THREAD

**Issue by MendioxCS** [JackBilbo/lxn-discus#16]
Hi there,

first of all gratefull you for your hard effort of bringing us a full LXN navigation device, it's amazing.

I was testing it last days and I found a bug with Saitek Radio Panel, when I tried to change radios or transponder it interferes with the panel, changing zoom, map orientation and so on.

Have you noticed it? Any fix?

Thank you,

M.

**Comment by JackBilbo** [comment]
Cheers. As they say: "it's not a bug, it's a feature" :-D Transponder and Com Radio settings are used to allow keybinding functions like Zoom and changing pages, since we have no custom key events available in MSFS. The events bound are listed in the readme file - or simply checkout the AS33 on flightsim.to - i adapted almost all keybings from there, to keep things consistent between gliders. 
I personally have a seperate Joystick profile for flying gliders, that allows me to scroll and zoom without using the mouse - very handy when circling close to a mountain side :-)
If you really want to use your radios and want to deactivate the keybinds, you would need to dive into the JS and deactivate these functions.
